// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Postsbaspana struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DatePublication time.Time
	Title           string
	Image           string
	CostForMetr     int32
	Address         string
	LinkDetailPost  string
	NumberObject    int32
	CountAccess     int32
	Region          string
}
