// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Postsbaspana struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Title          string
	Image          string
	CostForMetr    sql.NullInt32
	Address        string
	LinkDetailPost string
	NumberObject   sql.NullInt32
	CountAccess    sql.NullInt32
}
