// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO postsBaspana (
    id, 
    created_at, 
    updated_at, 
    title, 
    image, 
    cost_for_metr,
    address, 
    link_detail_post, 
    number_object, 
    count_access
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at, updated_at, title, image, cost_for_metr, address, link_detail_post, number_object, count_access
`

type CreatePostParams struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Title          string
	Image          string
	CostForMetr    sql.NullInt32
	Address        string
	LinkDetailPost string
	NumberObject   sql.NullInt32
	CountAccess    sql.NullInt32
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Postsbaspana, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Image,
		arg.CostForMetr,
		arg.Address,
		arg.LinkDetailPost,
		arg.NumberObject,
		arg.CountAccess,
	)
	var i Postsbaspana
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Image,
		&i.CostForMetr,
		&i.Address,
		&i.LinkDetailPost,
		&i.NumberObject,
		&i.CountAccess,
	)
	return i, err
}
